'use client';
import {useState} from 'react';
import {SEAFOOD,SEAFOOD_MODES,SEAFOOD_KINDS,type SeafoodMode,type SeafoodKind} from '@/lib/island-expansion-types';
import {equipmentName,isAquaticPet,petRoster,type ShopSnapshot,type ShopResult} from '@/lib/island-shop';
export function IslandSeaCarePanel({inventory,busy,select,equip,feed,command}:{inventory:ShopSnapshot;busy:boolean;select:(id:string)=>ShopResult;equip:(id:string)=>ShopResult;feed:(id:string)=>ShopResult;command:(id:string,c:'lesson'|'recall'|'pet')=>ShopResult}){
  const [message,setMessage]=useState('');const stock=inventory.expansion,selected=SEAFOOD.find(f=>f.id===stock?.selectedSeafood)??SEAFOOD[0];
  const choose=(mode:SeafoodMode,kind:SeafoodKind)=>setMessage(select(`${mode}-${kind}`).message);
  const available=stock?.seafood[selected.id]??0,ready=selected.mode==='frozen'?inventory.activeItem==='ice-box'&&(stock?.iceBlocks??0)>=5:inventory.activeItem===selected.id;
  return <section className="sea-care-controls" aria-label="Marine animal feeding and training"><h3>Isla’s seafood</h3><div className="sea-food-select"><label>Preparation<select value={selected.mode} disabled={busy} onChange={e=>choose(e.target.value as SeafoodMode,selected.kind)}>{SEAFOOD_MODES.map(m=><option key={m} value={m}>{m==='live'?'1 · Live prey':m==='frozen'?'2 · Frozen':'3 · Fresh-dead'}</option>)}</select></label><label>Food<select value={selected.kind} disabled={busy} onChange={e=>choose(selected.mode,e.target.value as SeafoodKind)}>{SEAFOOD_KINDS.map(k=><option key={k} value={k}>{k==='squid'?'Mini squid':k==='crab'?'Crab':'Marine fish'}</option>)}</select></label></div>
    <p>{available} portions · {stock?.iceBlocks??0} ice blocks in cooler</p><p>{selected.mode==='live'?'Dolphins and sea lions pursue live prey. Each successful meal adds 10 hunting points; higher skill makes them faster at catching it.':selected.mode==='frozen'?'Hold the ice box with at least five ice blocks. One block melts each new day.':'Fresh-dead seafood provides a meal without the hunting bonus.'}</p>
    <button className="care-secondary" disabled={busy||ready} onClick={()=>setMessage(equip(selected.mode==='frozen'?'ice-box':selected.id).message)}>{ready?'Food ready':selected.mode==='frozen'?'Hold ice box':'Equip seafood bucket'}</button>
    {petRoster(inventory).filter(p=>isAquaticPet(p.id)).map(p=>{const skills=stock?.skills[p.id]??{hunting:0,trust:0};return <div className="sea-pet-training" key={p.id}><strong>{equipmentName(p.id)}</strong><label>Hunting · {skills.hunting===100?'Wild-ready':`${skills.hunting}%`}<progress max={100} value={skills.hunting}/></label><label>Trust · {skills.trust}%<progress max={100} value={skills.trust}/></label><div><button disabled={busy||!ready||available<1} onClick={()=>setMessage(feed(p.id).message)}>{busy?'Animal busy…':selected.mode==='live'?'Pour live prey':'Serve seafood'}</button><button disabled={busy} onClick={()=>setMessage(command(p.id,'pet').message)}>Interact</button><button disabled={busy||!inventory.owned.includes('trainer')} onClick={()=>setMessage(command(p.id,'recall').message)}>Recall</button><button disabled={busy||!inventory.owned.includes('trainer')} onClick={()=>setMessage(command(p.id,'lesson').message)}>Trainer lesson</button></div></div>;})}
    <small>Wear chest waders or scuba for hands-on petting. Assign your hired trainer a budget for reward-based recall and lessons; he works without changing your outfit. Hunting strength is a game skill, not a claim about real animal rehabilitation.</small>{message&&<p role="status">{message}</p>}
  </section>;
}
