'use client';
import {useState} from 'react';
import {Waves} from 'lucide-react';
import {petRoster,isAquaticPet,equipmentName,type ShopSnapshot,type ShopResult} from '@/lib/island-shop';
import {ownedTier,homeCapacity,SEA_BREEDING,seaBroodStage} from '@/lib/island-habitat-types';
export function IslandSeaFamily({inventory,fish,start}:{inventory:ShopSnapshot;fish:number;start:(id:string)=>ShopResult}){
  const [selected,setSelected]=useState(''),[message,setMessage]=useState('');
  const sea=petRoster(inventory).filter(p=>isAquaticPet(p.species)),pairs=[...new Set(sea.map(p=>p.species))].filter(id=>sea.filter(p=>p.species===id).length>=2),id=pairs.includes(selected)?selected:pairs[0]??'',brood=inventory.seaBrood,tier=ownedTier(inventory,'sea'),meals=fish+(inventory.foodPortions??0);
  return <section className="sea-family-care"><h3><Waves size={18}/> Sea families</h3>{brood?<><p>{equipmentName(brood.species)} · {seaBroodStage(brood)==='expecting'?'Expecting a baby':seaBroodStage(brood)==='baby'?'A baby is following its parent':'Your youngster is growing up'}</p><progress value={brood.elapsed} max={SEA_BREEDING.grown} aria-label="Sea family growth"/><small>{Math.ceil(SEA_BREEDING.grown-brood.elapsed)} active-game seconds until adulthood. One space is reserved; your baby stays in this home.</small><p>8 meals and fresh seawater stocked.</p></>:<><label className="bird-choice">Choose two adults<select aria-label="Choose sea breeding pair" value={id} onChange={e=>setSelected(e.target.value)}>{!pairs.length&&<option value="">Two matching adults needed</option>}{pairs.map(p=><option key={p} value={p}>{equipmentName(p)} pair</option>)}</select></label><p>{tier==='basic'?'Upgrade to Standard or above to raise a baby.':!id?'Buy two dolphins or two sea lions from Isla.':'One baby per family. The parents and baby stay together in this home.'}</p><p>{meals} meals · {inventory.seawaterUses??0} seawater supplies available</p><button className="market-buy" disabled={!id||tier==='basic'||!tier||meals<8||!(inventory.seawaterUses??0)||sea.length>=homeCapacity(inventory,'sea')} onClick={()=>setMessage(start(id).message)}>Start sea family · 8 meals + 1 seawater</button><small>About 3 active-game minutes. Keep one free space for the baby.</small></>}<p className="market-receipt" role="status">{message}</p><small>{inventory.raisedSea??0} sea babies raised</small></section>;
}
