'use client';

import './coastal-life.css';
import {IslandCoastalPanel} from '@/components/island-coastal-panel';
import {IslandCabinStorage} from '@/components/island-cabin-storage';
import {seafoodSpec,rodLevel} from '@/lib/island-expansion-types';
import {IslandAdvancements} from '@/components/island-advancements';
import {emptyAdvancements} from '@/lib/island-advancements';
import {DISTANT_ISLANDS} from '@/lib/island-destinations';
import { useEffect, useRef, useState } from 'react';
import { Anchor, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, CloudFog, Coins, Compass, Eye, Fish, HelpCircle, Map, Moon, PersonStanding, RotateCcw, ShoppingBag, Sun, Wind, X } from 'lucide-react';
import type { CameraMode, IslandAPI, IslandStatus } from '@/lib/island-engine';
import { IslandShop } from '@/components/island-shop';
import { IslandHotbar, EquipmentIcon } from '@/components/island-hotbar';
import { equipmentName, usesRod, isPet, isBoat } from '@/lib/island-shop';
import { basketQuote } from '@/lib/island-shop';
import { IslandCashier } from '@/components/island-cashier';
import { IslandPetCare } from '@/components/island-pet-care';
import {IslandChart} from '@/components/island-chart';
import {outfitName,safeDepth} from '@/lib/island-water';
import {isBirdTool} from '@/lib/island-bird-tools';
import {IslandFamilyPanel} from '@/components/island-family-panel';
import {isSpeargun} from '@/lib/island-speargun-types';
import {IslandBirdPanel} from '@/components/island-bird-panel';

const initialStatus: IslandStatus = {bird:{id:null,phase:'home',message:'Open the aviary gate and whistle to call your bird.',doubleWindow:0,queued:false,petting:false},water:{depth:0,submerged:false,swimming:false,outfit:'regular'},spear:{phase:'ready',message:'Wear scuba gear, dive and aim at a fish · F to fire',remaining:0},navigation:{x:-29,z:54,heading:42,open:false,aboard:null,speed:0,rainforest:false},boatBusy:false, zone: 'Harbour beach', heading: 42, door: '', loading: 0, assetError: '', locked: false, health: 100, dead: false, notice: '', coins: 250, catches: 0, fishInBag:0, fishing: 'idle', fishingMessage: 'Face the water · F to cast', progress: 0, tension: .2, shop: {owned:[],equippedLure:null,hookEquipped:false,activeItem:'rod'},market:false,marketLoading:false,offer:null,cashier:false,care:null,petGates:{birds:false,sea:false},advice:'' };
export default function Home() {
  const host = useRef<HTMLDivElement>(null), api = useRef<IslandAPI | null>(null);
  const [status, setStatus] = useState(initialStatus);
  const [view, setView] = useState<CameraMode>('first');
  const night=(status.day?.night??0)>.55;
  const [mist, setMist] = useState(true), [drift, setDrift] = useState(false), [help, setHelp] = useState(false);
  const [ready, setReady] = useState(false), [error, setError] = useState('');
  const [fleetOpen,setFleetOpen]=useState(false);
  useEffect(() => {
    let cancelled = false;
    void import('@/lib/island-engine').then(({ createIsland }) => {
      if (cancelled || !host.current) return;
      try { api.current = createIsland(host.current, setStatus); setReady(true); }
      catch { setError('The 3D view could not start. Please reload with WebGL enabled in your browser.'); }
    }).catch(() => setError('The island could not load. Please reload to try again.'));
    return () => { cancelled = true; api.current?.dispose(); api.current = null; };
  }, []);
  const changeView = (next: CameraMode) => { setView(next); api.current?.setView(next); };
  const directions = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];
  const rodEquipped=usesRod(status.shop.activeItem);
  const casting=!!status.day?.exhausted||!!status.day?.sleeping||!!status.seaCare?.active||!!status.pelicanMeal?.active||['casting','waiting','bite','reeling','landing','scooping'].includes(status.fishing)||status.spear.phase!=='ready';
  const spearEquipped=isSpeargun(status.shop.activeItem);
  const birdEquipped=isBirdTool(status.shop.activeItem);
  const petEquipped=isPet(status.shop.activeItem),netEquipped=status.shop.activeItem==='net'; const careEquipped=!!seafoodSpec(status.shop.activeItem)||['food-can','seawater','menhaden','ice-box'].includes(status.shop.activeItem);
  const boatEquipped=isBoat(status.shop.activeItem),aboard=!!status.navigation.aboard;
  const ownedBoats=status.shop.owned.filter(isBoat);
  const launch=(id:string)=>{if(view==='overview')changeView('first');setFleetOpen(false);void api.current?.launchBoat(id);};
  if(status.day?.exhausted)return <main className="exhausted-screen" role="alert"><p>Your energy ran out.<br/>Reload the game to start a new visit.</p></main>;
  return (
    <main className={`island-game ${night ? 'night' : ''} ${status.market?'at-market':''} ${view==='overview'?'overview-mode':''}`}>
      <div className="world" ref={host} />
      <div className="view-vignette" />
      {status.day?.sleeping&&<div className="sleep-screen" role="status">Resting until morning…</div>}
      {status.day&&<section className={`day-energy ${status.day.energy<20?'low-energy':''}`} aria-label="Day and energy"><div><strong>Day {status.day.day}</strong><time>{String(Math.floor(status.day.hour)).padStart(2,'0')}:{String(Math.floor(status.day.hour%1*60)).padStart(2,'0')}</time><span>Sleep is free</span></div><label>Energy {Math.ceil(status.day.energy)}%<progress value={status.day.energy} max={100}/></label><small>{status.day.energy<20?'Return to your cabin bed before energy reaches zero.':'E by your bed to sleep · 20-minute day/night cycle'}{status.day.taxDue>0?` · ${status.day.taxDue} coins tax due`:''}</small></section>}
      {status.storage&&<IslandCabinStorage inventory={status.shop} store={id=>api.current?.storeItem(id)??{ok:false,message:'Loading'}} retrieve={id=>api.current?.retrieveItem(id)??{ok:false,message:'Loading'}} close={()=>api.current?.closeStorage()}/>}

      {view!=='overview'&&status.water.submerged&&<div className="underwater-tint" aria-hidden="true"/>}
      {!ready && <div className="loading-screen" role="status"><Compass size={34} className="loading-compass" /><h1>Tide Island</h1><p>{error || 'The coast is calling…'}</p>{error && <button onClick={() => window.location.reload()}>Reload island</button>}</div>}
      <header className="game-header">
        <div className="player-stats"><div className="coin-budget" aria-label={`Coin budget: ${status.coins} coins`}><span className="coin-disc"><Coins size={20} strokeWidth={2.3} /></span><strong>{status.coins}</strong><span className="coin-unit">coins</span></div><div className="health-stat"><span>Health <b>{status.health}</b></span><progress value={status.health} max={100} aria-label="Health" /></div>{status.catches > 0 && <span className="catch-count">{status.catches} fish caught</span>}</div>
        <div className="compass" aria-label={`Facing ${Math.round(status.heading)} degrees`}><span className="compass-tick" /><span>{directions[(Math.round(status.heading / 45) + 7) % 8]}</span><b>{directions[Math.round(status.heading / 45) % 8]}</b><span>{directions[(Math.round(status.heading / 45) + 1) % 8]}</span><small>{String(Math.round(status.heading)).padStart(3, '0')}°</small></div>
        <div className="header-actions"><button className="open-shop" aria-label={status.market?'Return to Tide Island':'Travel to Market Island'} disabled={!ready||status.dead||casting} onClick={()=>{if(view==='overview')changeView('first');api.current?.travelMarket();}} title={status.market?'Return to Tide Island for free':'Teleport to Market Island for free'}><ShoppingBag size={18}/><span>{status.market?'Return home':'Market Island'}</span></button><button className="round-button" aria-label="Return to harbour" title="Return to harbour" onClick={() => api.current?.reset()}><RotateCcw size={18} /></button><button className="round-button" aria-label="Show controls" title="Controls" onClick={() => setHelp(!help)}><HelpCircle size={19} /></button></div>
      </header>
      <IslandCoastalPanel status={status} api={api.current}/>
      <IslandAdvancements progress={status.advancements??emptyAdvancements()}/>
      {view!=='overview'&&!status.market&&!aboard&&<aside className={`water-status ${status.water.outfit!=='scuba'&&status.water.depth>safeDepth(status.water.outfit)*.78?'water-danger':''}`} aria-label="Water safety"><strong>{outfitName(status.shop.outfit??'regular')}</strong>{status.water.outfit==='snorkel'?<><span>{status.water.swimming?'SURFACE SNORKELING':'READY TO SNORKEL'}</span><p>WASD swims · look down through your mask. Scuba is needed for deep diving.</p></>:status.water.outfit==='scuba'?<><span>{status.water.submerged?'UNDERWATER':status.water.swimming?'AT THE SURFACE':'READY TO DIVE'}</span><p>Depth {Math.max(0,status.water.depth-1.62).toFixed(1)} m · Space ↑ · C ↓</p></>:<><span>{status.water.depth.toFixed(2)} m / {safeDepth(status.water.outfit).toFixed(2)} m safe</span><progress aria-label="Wading depth" value={status.water.depth} max={safeDepth(status.water.outfit)}/><p>{status.water.depth>safeDepth(status.water.outfit)*.78?'Too deep ahead—turn back!':status.water.outfit==='waders'?'Waterproof · clothes stay dry':'Waist-deep only · deeper water is fatal'}</p></>}</aside>}
      {status.shop.chartUnlocked&&<button className="chart-toggle" aria-pressed={status.navigation.open} onClick={()=>api.current?.toggleChart()}><Map size={19}/><span>Sea chart</span><kbd>M</kbd></button>}
      {ownedBoats.length>0&&<button className="fleet-toggle" aria-expanded={fleetOpen} onClick={()=>setFleetOpen(!fleetOpen)}><Anchor size={18}/>My boats <span>{ownedBoats.length}</span></button>}
      {fleetOpen&&<section className="fleet-panel" aria-label="My owned boats"><div className="chart-heading"><Anchor size={18}/><strong>My boats</strong><button aria-label="Close my boats" onClick={()=>setFleetOpen(false)}><X size={18}/></button></div><p>Already paid for. Launching is free and takes you to your home harbour.</p>{ownedBoats.map(id=><div className="fleet-row" key={id}><span>{equipmentName(id)}<small>Owned · paddle included for kayaks</small></span><button disabled={aboard||casting||status.dead||status.boatBusy} onClick={()=>launch(id)}>Launch & drive</button></div>)}{aboard&&<small>Step ashore before switching boats.</small>}<small>Purchases currently last for this visit.</small></section>}
      {status.shop.chartUnlocked&&status.navigation.open&&<IslandChart navigation={status.navigation} close={()=>api.current?.toggleChart()}/>}
      {view!=='overview'&&!status.cashier&&!status.offer&&(boatEquipped||aboard)&&<section className="sailing-panel" aria-label="Boat controls"><span className="sailing-eyebrow"><Anchor size={17}/>{aboard?'AT THE HELM':'OWNED · READY TO SAIL'}</span><h2>{equipmentName(status.navigation.aboard??status.shop.activeItem)}</h2>
        <p>{aboard?`${(status.navigation.speed*1.94).toFixed(1)} knots · W/S move & reverse · A/D steer`:'Your boat is paid for. Launch & drive takes you straight aboard at your home harbour.'}</p>
        <button className="fish-action" disabled={status.boatBusy||status.dead||casting} onClick={()=>aboard?void api.current?.boatAction():launch(status.shop.activeItem)}>{aboard&&<kbd>E</kbd>}{status.boatBusy?'Launching…':aboard?'Step ashore':'Launch & drive'}</button>
        <small>{aboard?'Release W/S to stop beside a beach or dock. E steps ashore; E nearby boards again. M opens your chart.':'No extra coins or shipping charge. My boats lists every boat you own. M opens routes to Rainwild, Pearl Atoll, Ember Isle and Frosthaven.'}</small>
      </section>}
      {status.offer&&<IslandShop key={status.offer} id={status.offer} applyLicence={a=>api.current?.applyLicence(a)??{ok:false,message:'Still loading.'}} close={()=>api.current?.closeOffer()} coins={status.coins} inventory={status.shop} buy={id=>api.current?.buy(id)??Promise.resolve({ok:false,message:'Island is still loading.'})} equip={id=>api.current?.equip(id)??{ok:false,message:'Island is still loading.'}}/>}
      {status.cashier&&<IslandCashier inventory={status.shop} coins={status.coins} advice={status.advice} ask={topic=>api.current?.askCashier(topic)} remove={id=>api.current?.removeBasket(id)} pay={()=>api.current?.checkout()??Promise.resolve({ok:false,message:'Still loading.'})} launchBoat={launch} close={()=>api.current?.closeCashier()}/>}
      {status.familyCare&&<IslandFamilyPanel inventory={status.shop} fish={status.fishInBag} away={status.bird.phase!=='home'?status.bird.id:null} gateOpen={!!status.familyGateOpen} start={id=>api.current?.startBrood(id)??{ok:false,message:'Still loading.'}} toggleGate={()=>api.current?.toggleFamilyGate()??{ok:false,message:'Still loading.'}} close={()=>api.current?.closeFamily()}/>}
      {status.care&&<IslandPetCare trainer={status.trainer?{state:status.trainer,coins:status.coins,fund:n=>api.current?.fundTrainer(n)??{ok:false,message:'Loading'},pause:()=>api.current?.pauseTrainer(),resume:()=>api.current?.resumeTrainer()??{ok:false,message:'Loading'},reclaim:()=>api.current?.reclaimTrainer()??{ok:false,message:'Loading'}}:undefined} selectSeafood={id=>api.current?.selectSeafood(id)??{ok:false,message:'Loading'}} serveSeafood={id=>api.current?.serveSeafood(id)??{ok:false,message:'Loading'}} seaCommand={(id,c)=>api.current?.seaCommand(id,c)??{ok:false,message:'Loading'}} busy={!!status.pelicanMeal?.active||!!status.seaCare?.active||!!status.trainerBusy} key={status.care} home={status.care} coins={status.coins} expand={tiles=>api.current?.expandHabitat(status.care!,tiles)??{ok:false,message:'Still loading.'}} startSea={id=>api.current?.startSeaBrood(id)??{ok:false,message:'Still loading.'}} gateOpen={status.petGates[status.care]} toggleGate={()=>api.current?.togglePetGate(status.care!)??{ok:false,message:'Still loading.'}} inventory={status.shop} fish={status.fishInBag} feed={id=>api.current?.feedResident(id)??{ok:false,message:'Still loading.'}} water={()=>api.current?.refreshHabitat()??{ok:false,message:'Still loading.'}} design={value=>api.current?.customiseCan(value)??{ok:false,message:'Still loading.'}} equip={id=>api.current?.equip(id)??{ok:false,message:'Still loading.'}} close={()=>api.current?.closeCare()}/>}
      {status.trainer?.hired&&!status.care&&!status.market&&status.trainerBusy&&<aside className="trainer-watch" aria-label="Trainer activity"><strong>Your trainer is working</strong><p>{status.trainer.message}</p><small>{status.trainer.balance} coins left in his budget · E near him to manage</small></aside>}
      {status.market&&!status.offer&&!status.cashier&&<div className="market-guide"><strong>Welcome to Saltwater Market</strong><p>West: boats, tackle & diving<br/>East: animals & habitats<br/>South: seafood & care supplies</p><p><kbd>E</kbd> Inspect displays · pay Coral in the square</p><small>Prices include shipping. 4+ items in one purchase category: 10% off goods.</small><p>Basket: {basketQuote(status.shop.basket).count} items · {basketQuote(status.shop.basket).total} coins</p>{status.marketLoading&&<p role="status">Stock is arriving…</p>}</div>}
      {ready && status.loading < 100 && <div className="asset-loading" role="status"><span style={{ width: `${status.loading}%` }} /><p>Bringing the island to life <b>{status.loading}%</b></p></div>}
      {status.assetError && <p className="asset-notice" role="status">{status.assetError}</p>}
      {status.notice && <div className={`world-notice ${status.dead ? 'is-fatal' : ''}`} role="status">{status.notice}</div>}
      {view !== 'overview' && <div className="crosshair" aria-hidden="true" />}
      {status.door && <button className="interact-prompt" onClick={() => api.current?.interact()}><kbd>E</kbd>{status.door}</button>}
      <div className="location-panel"><span className="location-overline"><Anchor size={13} /> {status.market?'THE TRADING ISLAND':status.navigation.distant?'THE DISTANT ISLANDS':status.navigation.rainforest?'THE RAINFOREST ISLAND':aboard?'THE OPEN SEA':'THE WILD COAST'}</span><h1>{status.market?'Saltwater Market':status.navigation.distant?DISTANT_ISLANDS.find(i=>i.id===status.navigation.distant)?.name:status.navigation.rainforest?'Rainwild Island':'Tide Island'}<span> / </span><em>{status.market?'Free return voyage':status.zone}</em></h1><p>{view === 'overview' ? 'Drag to orbit · Scroll to explore' : aboard?'W/S throttle · A/D steer · M navigation chart':status.locked ? 'WASD to explore · Shift to run · Esc to release mouse' : 'WASD to explore · Click or drag the scene to look'}</p></div>
      {view !== 'overview' && !status.market&&!aboard&&!boatEquipped && <div className="equipment-label"><EquipmentIcon id={status.shop.activeItem}/><div><span>{equipmentName(status.shop.activeItem)}</span><strong>{rodEquipped?`LEVEL ${rodLevel(status.shop.expansion?.rod??'rod')} ROD`:'IN HAND'}</strong></div></div>}
      {view !== 'overview' && <IslandHotbar inventory={status.shop} disabled={!ready||status.dead||casting||aboard||status.boatBusy} onEquip={id=>api.current?.equip(id)} onPage={delta=>api.current?.hotbarPage(delta)}/>}
      {view!=='overview'&&!status.market&&!aboard&&spearEquipped&&!status.familyCare&&<section className="fishing-panel spear-panel" aria-label="Spearfishing"><div className="fishing-title"><EquipmentIcon id={status.shop.activeItem}/><span>{equipmentName(status.shop.activeItem)} · SPEARFISHING</span></div><p role="status">{status.spear.message}</p><button className="fish-action" disabled={status.dead||casting||!status.water.submerged||status.water.outfit!=='scuba'} onClick={()=>api.current?.fish()}><kbd>F</kbd>{status.spear.phase==='ready'?'Fire spear':`${status.spear.phase==='reloading'?'Reloading':status.spear.phase==='retrieving'?'Retrieving':'Firing'}… ${status.spear.remaining.toFixed(1)}s`}</button><small>{status.water.outfit!=='scuba'?'Wear the scuba suit on dry land first.':!status.water.submerged?'Enter deep water, then hold C to dive.':'Aim at a fish within 12 m. Automatic retrieval and reload.'}</small></section>}
      {view!=='overview'&&!status.market&&!aboard&&!status.care&&!status.familyCare&&birdEquipped&&<IslandBirdPanel bird={status.bird} inventory={status.shop} disabled={status.dead||casting} whistle={()=>api.current?.whistle()} pet={()=>api.current?.petBird()} select={id=>api.current?.selectBird(id)} home={()=>api.current?.returnBird()}/>}
      {view !== 'overview' && !status.market && !status.care&&!status.familyCare && !rodEquipped&&!boatEquipped&&!aboard&&!spearEquipped&&!birdEquipped && <section className={`fishing-panel carried-panel phase-${status.fishing}`} aria-label="Carried equipment"><div className="fishing-title"><EquipmentIcon id={status.shop.activeItem}/><span>{netEquipped?'SCOOP FISH':petEquipped?'YOUR PET':careEquipped?'PET CARE':'IN HAND'}</span></div>
        <p role="status">{status.fishingMessage}</p>
        {(seafoodSpec(status.shop.activeItem)||status.shop.activeItem==='ice-box')&&<p className="pet-food">{status.shop.activeItem==='ice-box'?`${status.shop.expansion?.iceBlocks??0} ice blocks · Select frozen seafood at the sea home`:`${status.shop.expansion?.seafood[status.shop.activeItem]??0} portions · Dolphins & sea lions`}</p>}
        {status.shop.activeItem==='menhaden'&&<p className="pet-food"><strong>{status.shop.menhaden??0}</strong> Menhaden left · Pelicans only</p>}
        {petEquipped&&<p className="pet-food">Fish available: <strong>{status.fishInBag}</strong> · Meals: {status.shop.petMeals?.[status.shop.activeItem]??0}</p>}
        <div className="fishing-actions">{(netEquipped||petEquipped||careEquipped||status.shop.activeItem==='knife'||status.shop.activeItem==='bow')&&<button className="fish-action" disabled={status.dead||casting||petEquipped&&status.fishInBag<1||status.shop.activeItem==='menhaden'&&!(status.shop.menhaden??0)} onClick={()=>api.current?.fish()}><kbd>F</kbd>{status.pelicanMeal?.active||status.seaCare?.active?'Feeding…':seafoodSpec(status.shop.activeItem)?'Pour seafood':status.shop.activeItem==='ice-box'?'Serve frozen food':status.shop.activeItem==='menhaden'?'Toss 1 Menhaden':status.fishing==='scooping'?'Scooping…':status.shop.activeItem==='seawater'?'Refresh water':status.shop.activeItem==='food-can'?'Feed a resident':petEquipped?'Feed 1 fish':status.shop.activeItem==='knife'?'Prepare held fish':status.shop.activeItem==='bow'?'Shoot arrow':'Scoop'}</button>}<button className="fish-action" disabled={status.dead||casting} onClick={()=>api.current?.equip('rod')}><kbd>1</kbd>Rod</button></div>
      </section>}
      {view !== 'overview' && !status.market && !status.care&&!status.familyCare && rodEquipped&&!aboard && <section className={`fishing-panel phase-${status.fishing}`} aria-label="Fishing">
        <div className="fishing-title"><Fish size={17} /><span>{status.fishing === 'landing' ? 'BRINGING IT IN' : status.fishing === 'caught' ? 'CATCH LANDED' : status.fishing === 'bite' ? 'FISH ON!' : 'SHORE FISHING'}</span></div>
        <p role="status">{status.fishingMessage}</p>
        {status.fishing === 'reeling' && <div className="fishing-meters"><label>Reel progress <progress value={status.progress} max={1} /></label><label>Line tension <meter value={status.tension} min={0} max={1} low={.3} high={.78} optimum={.4} /></label><small>{status.tension > .78 ? 'Ease off! Release to save your line.' : 'Hold to reel · release to lower tension'}</small></div>}
        <div className="fishing-actions">
          {status.fishing === 'reeling' ? <button className="fish-action" disabled={status.dead} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); api.current?.reel(true); }} onPointerUp={() => api.current?.reel(false)} onPointerCancel={() => api.current?.reel(false)} onLostPointerCapture={() => api.current?.reel(false)} onKeyDown={e => { if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); api.current?.reel(true); } }} onKeyUp={() => api.current?.reel(false)} onBlur={() => api.current?.reel(false)}><kbd>R</kbd>Hold to reel</button> : <button className="fish-action" disabled={status.dead || ['casting', 'waiting', 'landing'].includes(status.fishing)} onClick={() => api.current?.fish()}><kbd>F</kbd>{status.fishing === 'landing' ? 'Landing your fish…' : status.fishing === 'bite' ? 'Hook fish!' : status.fishing === 'waiting' ? 'Waiting for a bite' : status.fishing === 'casting' ? 'Casting…' : 'Cast line'}</button>}
          {['casting', 'waiting', 'bite', 'reeling'].includes(status.fishing) && <button className="cancel-cast" onClick={() => api.current?.cancelCast()} title="X to retrieve line">Retrieve</button>}
        </div>
      </section>}
      {view !== 'overview'&&!aboard&&!status.water.swimming && <button className="jump-button" aria-label="Jump" disabled={status.dead} onClick={() => api.current?.jump()}><ArrowUp size={18} /><span>Jump</span><kbd>Space</kbd></button>}
      {view!=='overview'&&!aboard&&status.water.swimming&&status.water.outfit==='scuba'&&<div className="dive-controls" aria-label="Diving controls">{[[' ','Rise','Space'],['c','Dive','C']].map(([key,label,hint])=><button key={key} disabled={status.dead} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);api.current?.setMove(key,true);}} onPointerUp={()=>api.current?.setMove(key,false)} onPointerCancel={()=>api.current?.setMove(key,false)} onLostPointerCapture={()=>api.current?.setMove(key,false)} onKeyDown={e=>{if(e.key==='Enter')api.current?.setMove(key,true);}} onKeyUp={()=>api.current?.setMove(key,false)} onBlur={()=>api.current?.setMove(key,false)}>{label}<kbd>{hint}</kbd></button>)}</div>}
      <nav className="game-toolbar" aria-label="Island controls">
        <div className="view-selector" role="group" aria-label="Camera view">
          <button className={view === 'first' ? 'selected' : ''} aria-pressed={view === 'first'} onClick={() => changeView('first')} title="First person"><Eye size={17} /><span>First person</span></button>
          <button className={view === 'third' ? 'selected' : ''} aria-pressed={view === 'third'} onClick={() => changeView('third')} title="Third person"><PersonStanding size={17} /><span>Third person</span></button>
          <button className={view === 'overview' ? 'selected' : ''} aria-pressed={view === 'overview'} onClick={() => changeView('overview')} title="Island overview"><Compass size={17} /><span>Island</span></button>
        </div>
        <div className="toolbar-divider" />
        <span className="setting-button" title="Automatic day/night cycle">{night ? <Moon size={18} /> : <Sun size={18} />}</span>
        <button className={`setting-button ${mist ? 'enabled' : ''}`} aria-label="Sea mist" aria-pressed={mist} title="Sea mist" onClick={() => { setMist(!mist); api.current?.setMist(!mist); }}><CloudFog size={18} /></button>
        {view === 'overview' && <button className={`setting-button ${drift ? 'enabled' : ''}`} aria-label="Slowly orbit island" aria-pressed={drift} title="Auto orbit" onClick={() => { setDrift(!drift); api.current?.setDrift(!drift); }}><Wind size={18} /></button>}
      </nav>
      {view !== 'overview' && <div className="touch-movement" aria-label="Movement controls">{[['w', ArrowUp], ['a', ArrowLeft], ['s', ArrowDown], ['d', ArrowRight]].map(([key, Icon]) => { const MoveIcon = Icon as typeof ArrowUp; return <button key={key as string} className={`move-${key}`} aria-label={`Move ${key === 'w' ? 'forward' : key === 's' ? 'backward' : key === 'a' ? 'left' : 'right'}`} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); api.current?.setMove(key as string, true); }} onPointerUp={() => api.current?.setMove(key as string, false)} onPointerCancel={() => api.current?.setMove(key as string, false)}><MoveIcon size={21} /></button>; })}</div>}
      {help && <div className="help-backdrop" onClick={() => setHelp(false)}><section className="help-panel" role="dialog" aria-modal="true" aria-label="Island controls" onClick={e => e.stopPropagation()}><button className="close-help" autoFocus aria-label="Close controls" onClick={() => setHelp(false)}><X size={20} /></button><Compass size={28} /><h2>Find your own shore.</h2><p>Regular clothes allow waist-deep wading; keeper’s waders keep clothes dry to chest depth. Snorkeling gear lets you swim at the surface and look underwater; scuba lets you dive. Exceeding your outfit’s safe depth is fatal. Buy water gear from Finn and change on dry land.</p><dl><div><dt>Walk / swim / run</dt><dd>W A S D / Shift</dd></div><div><dt>Jump / scuba swim up</dt><dd>Space</dd></div><div><dt>Dive with scuba</dt><dd>Hold C</dd></div><div><dt>Cast / hook / fire spear / pet bird</dt><dd>F or left click*</dd></div><div><dt>Call bird / send it fishing</dt><dd>G / two G less than 3s apart</dd></div><div><dt>Reel / ease tension</dt><dd>Hold / release R</dd></div><div><dt>Retrieve fishing line</dt><dd>X</dd></div><div><dt>Look around</dt><dd>Click or drag scene</dd></div><div><dt>Visit the market</dt><dd>Market Island button</dd></div><div><dt>Shop / talk / doors & gates</dt><dd>E when nearby</dd></div><div><dt>Close quote / release mouse</dt><dd>Esc</dd></div></dl><small>*After capturing the mouse. Buy the glove and whistle from Isla; call an owned bird at its open aviary gate. Birds eat their catch and return to your glove. The speargun needs scuba and a submerged player; aim within 12 m. Purchases and catches last for this visit.</small></section></div>}
    </main>
  );
}
