import assert from 'node:assert/strict';
import {CatchWork,DRYING_SECONDS,fishValue} from '../lib/island-catch-work';
import {ShopInventory} from '../lib/island-shop';
import {CoastalDeliveries} from '../lib/island-deliveries';
import {DELIVERY_ARRIVAL_SECONDS} from '../lib/island-delivery-route';
import {FishingGame,type FishAgent} from '../lib/island-fishing';
import {FishingBow} from '../lib/island-bow';
import {IslandDay,DAY_SECONDS} from '../lib/island-day-cycle';
import {validPose} from '../lib/crew-protocol';
const fish:FishAgent={id:'test',name:'Atlantic mackerel',position:{x:0,y:-.7,z:300},target:null,caught:false,catchable:true,clearance:.1,length:.6,value:20,weight:.5};
const work=new CatchWork(),game=new FishingGame([fish]);game.onLand=f=>work.add(f);const coins=game.coins;
assert(game.claimSpearCatch(fish));assert.equal(game.coins,coins);assert.equal(work.holding?.name,fish.name);assert(!game.claimSpearCatch(fish));assert.equal(work.fish.length,1);
assert(!work.hang(work.held!));assert(work.knife());work.update(2);assert.equal(work.holding?.state,'dead');const id=work.held!;assert(work.hang(id));assert.equal(work.held,null);assert(!work.hang(id));work.update(DRYING_SECONDS/2);assert(work.retrieve(id));assert.equal(fishValue(work.holding!),28);assert(work.list(id,100));assert(!work.customer('Nora',game));assert(work.list(id,28));assert(work.customer('Nora',game));assert.equal(game.coins,coins+28);assert(!work.customer('Kai',game));
const shop=new ShopInventory(),delivery=new CoastalDeliveries(shop),wallet={coins:10000};shop.dispatch=o=>delivery.order(o);shop.basket={'bird-home-basic':1,'pet-seagull':2,'knife':1};const before=wallet.coins;assert(shop.checkout(wallet).ok);assert(wallet.coins<before);assert(!shop.owned.has('knife'));assert(!shop.addToBasket('knife').ok);shop.basket={'pet-seagull':1};assert(!shop.checkout(wallet).ok);shop.basket={};
for(let i=0;i<Math.ceil(DELIVERY_ARRIVAL_SECONDS*10)+1;i++)delivery.update(.1,true);assert(shop.owned.has('bird-home'));assert.equal(shop.petCounts['pet-seagull'],undefined);assert(delivery.collect());for(let i=0;i<11;i++)delivery.update(.1,true);assert.equal(delivery.cages.length,1);assert(!shop.owned.has('pet-seagull'));assert(delivery.deploy());assert.equal(shop.petCounts['pet-seagull'],2);assert(!delivery.deploy());
for(let i=0;i<180;i++)delivery.update(.1,true);assert(delivery.collect());for(let i=0;i<11;i++)delivery.update(.1,true);assert(shop.owned.has('knife'));assert(!delivery.collect());
const day=new IslandDay(),savings={coins:100};day.elapsed=DAY_SECONDS-.3;day.energy=20;assert(day.sleep());while(day.sleeping>0)day.update(.1,0,savings,()=>{});assert.equal(savings.coins,100);assert.equal(day.energy,100);assert.equal(day.day,2);
assert.equal(validPose({x:Infinity,y:0,z:0,yaw:0}),null);assert.equal(validPose({x:0,y:0,z:0,yaw:0,outfit:'admin',action:'delete',boat:null})?.outfit,'regular');
const target={...fish,id:'bow',caught:false,position:{x:0,y:-.25,z:303}};const bow=new FishingBow([target],()=>false);bow.fire({x:0,y:1,z:306},{x:0,y:-.4,z:-1});for(let i=0;i<40;i++)bow.update(.02);assert(target.injured);assert(!target.caught);
console.log('PASS: held catches, knife, drying value, no duplicate sales, queued deliveries, bird-cage deployment, pending capacity, free sleep, bow hit, pose validation.');
