import assert from 'node:assert/strict';
import {ShopInventory,petRoster,availableBirds,basketQuote} from '../lib/island-shop';
const wallet={coins:100000},inv=new ShopInventory();
assert(!inv.buy('meandros-b32',wallet).ok);assert(!inv.addToBasket('meandros-b32').ok);assert(!inv.equip('meandros-b32').ok);
assert(!inv.applyLicence({equipment:'waders',targets:'wild-fish',agree:true},wallet).ok);assert.equal(wallet.coins,100000);
assert(inv.applyLicence({equipment:'scuba',targets:'wild-fish',agree:true},wallet).ok);assert.equal(wallet.coins,99950);
assert(inv.applyLicence({equipment:'scuba',targets:'wild-fish',agree:true},wallet).ok);assert.equal(wallet.coins,99950);
assert(inv.buy('meandros-b32',wallet).ok);assert(inv.equip('meandros-b32').ok);
for(const id of ['bird-home','family-aviary','family-nest','family-perch','family-feeder','pet-seagull','pet-seagull'])assert(inv.addToBasket(id).ok);
const q=basketQuote(inv.basket);assert.equal(q.lines.find(l=>l.item.id==='pet-seagull')?.quantity,2);assert.equal(q.shipping,30);assert(q.discount>0);assert(inv.checkout(wallet).ok);
assert.equal(petRoster(inv.snapshot()).length,2);assert.equal(petRoster(inv.snapshot())[1].id,'pet-seagull#2');
const food={fishInBag:5};assert(!inv.startBrood('pet-seagull',null,food).ok);assert.equal(food.fishInBag,5);
food.fishInBag=6;assert(!inv.startBrood('pet-seagull','pet-seagull#2',food).ok);
assert(inv.startBrood('pet-seagull',null,food).ok);assert.equal(food.fishInBag,0);assert.equal(availableBirds(inv.snapshot()).length,0);
assert(!inv.startBrood('pet-seagull',null,food).ok);
for(let i=0;i<3041;i++)inv.updateFamily(.05);
assert.equal(inv.familyBrood,null);assert.equal(inv.raisedBirds,2);assert.equal(petRoster(inv.snapshot()).length,4);assert.equal(availableBirds(inv.snapshot()).length,4);
assert(inv.buy('pet-seagull',wallet).ok);assert.equal(petRoster(inv.snapshot()).length,5);
assert(inv.buy('food-can',wallet).ok);assert(inv.startBrood('pet-seagull',null,food).ok);assert.equal(inv.foodPortions,0);
for(let i=0;i<18;i++)assert(inv.addToBasket('pet-seagull').ok);assert(!inv.checkout(wallet).ok);
const insufficient=new ShopInventory();assert(!insufficient.applyLicence({equipment:'scuba',targets:'wild-fish',agree:true},{coins:49}).ok);
const incomplete=new ShopInventory();for(const id of ['bird-home','family-aviary','pet-seagull','pet-seagull'])assert(incomplete.buy(id,wallet).ok);assert(!incomplete.startBrood('pet-seagull',null,{fishInBag:6}).ok);
console.log('PASS: permit guards, validation, single charge, repeat pet orders, shipping/discounts, individual IDs, breeding prerequisites, food, full growth cycle, parent availability and capacity reservations.');
